const files = {
  "card-header": {
    raceId: "1888910",
    races: {
      101702: {
        meeting_abandoned: 0,
        track: "Waterford",
        races: [
          { raceId: "1888910", raceDate: "2022-02-17", raceTime: "8:12" },
          { raceId: "1888911", raceDate: "2022-02-17", raceTime: "8:27" },
          { raceId: "1888912", raceDate: "2022-02-17", raceTime: "8:43" },
          { raceId: "1888913", raceDate: "2022-02-17", raceTime: "9:02" },
          { raceId: "1888914", raceDate: "2022-02-17", raceTime: "9:18" },
          { raceId: "1888915", raceDate: "2022-02-17", raceTime: "9:34" },
          { raceId: "1888916", raceDate: "2022-02-17", raceTime: "9:52" },
          { raceId: "1888917", raceDate: "2022-02-17", raceTime: "10:07" },
          { raceId: "1888918", raceDate: "2022-02-17", raceTime: "10:23" },
          { raceId: "1888919", raceDate: "2022-02-17", raceTime: "10:41" },
        ],
        track_id: "58",
        tv_id: "",
        tv_name: "",
      },
    },
    courseId: 101702,
    country: "IRE",
    trackAbbrName: "W'ford",
  },
  "card-title": {
    postPick: "6-3-4",
    napNum: "",
    raceSisStatusTopicD5: "GREYHOUNDS/2022-02-17/WATERFORD/08:12/#SIS_STATUS",
    infoTopicD5:
      "GREYHOUNDS/2022-02-17/WATERFORD/08:12/OUTRIGHT WINNER/#INFO/PREFERRED_BOOKMAKER",
    priceTopicD5:
      "GREYHOUNDS/2022-02-17/WATERFORD/08:12/OUTRIGHT WINNER/PREFERRED_DOG/PREFERRED_BOOKMAKER",
    testingPriceTopic:
      "GREYHOUNDS/2022-02-17/WATERFORD/08:12/OUTRIGHT WINNER/PREFERRED_DOG/PREFERRED_BOOKMAKER",
    distance: 480,
    raceGrade: "A5",
    raceTypeDesc: "Flat",
    raceDatetime: "1645085520",
    raceHour: "08",
    raceMin: "12",
    reserved: "",
    tvId: "",
    bagsCode: "S",
    raceTitle: "Race 1",
  },
  "card-tabs": {
    raceId: "1888910",
    raceDate: "2022-02-17 08:12",
    distance: "480",
    raceStatus: 0,
    raceTitle: "Welcome To Kilcohan Park 525",
    bagsCode: "S",
    trackName: "WATERFORD",
    trackCde: "WATE",
    rpTrackShortName: "Wtrfd",
    trackId: "58",
    country: "IRE",
    typeDesc: "Flat",
    raceGrade: "A5",
    selTrapNum: "6",
    tvId: "",
    dangerTrapNum: "3",
    fcastAltTrapNum: "4",
    napNum: "",
    raceDateDate: "2022-02-17",
    raceDateTime: "08:12",
  },
  form: {
    dogs: [
      {
        bestTimeGrade: "A4",
        bestTimeGradeDate: "23Dec21",
        birthMonYY: "Mar18",
        brt: "29.38",
        chanceOfWin: "",
        dam: "Fahrenheit Katie",
        dateOfBirth: "09Mar18",
        dateOfSeason: "",
        diffusionName: "DARING_TEGO",
        dogColor: "WBK",
        dogId: "543652",
        dogName: "Daring Tego",
        dogSex: "D",
        forecast: "11/4",
        forecastComment: "Odds off-putting, better propositions around",
        handicapMetre: "",
        isVacant: false,
        nonRunner: "Y",
        reserved: "",
        shortForm: "",
        sire: "Knockglass Billy",
        spotlightComment: "",
        topSpeed: "97",
        trackId: "58",
        trainerLocation: "",
        trainerName: "M Meade",
        trapNum: "1",
        wideYn: "",
        forms: [
          {
            bndPos: "2243",
            by: "3&frac12",
            calcRTimes: "29.74",
            clipId: "",
            closeUpCmnt: "EP,Ld1",
            handicapMetre: "",
            distanceTitle: "480m",
            goingType: "+10",
            gradeCde: "A5",
            oddsDesc: "2/1F",
            otherDHandicapMetre: "",
            otherDTxt: "Almighty Emma",
            otherDogId: 553423,
            otherDogName: "Almighty Emma",
            outcomeDesc: "2nd",
            rOutcomeId: "2",
            raceGradeId: "10",
            raceId: 1886130,
            raceTime: "2022-02-03 08:12",
            raceTitle: "Failte Go Dti Staid Kilcohan Park Na Gcon 525",
            resultDate: "03Feb22",
            resultsAvailable: 1,
            sectionalTime: "3.37",
            shortTracName: "Wtrfd",
            trackId: "58",
            trackName: "WATERFORD",
            trap: "2",
            trialFlag: "NT",
            typeCde: "F",
            videoid: "",
            weight: "36.8",
            winnersTimeS: "29.40",
          },
          {
            bndPos: "5555",
            by: "8&frac12",
            calcRTimes: "29.85",
            clipId: "",
            closeUpCmnt: "Fcd-Ck2,NvrShwd",
            handicapMetre: "",
            distanceTitle: "480m",
            goingType: "+10",
            gradeCde: "A4",
            oddsDesc: "5/2",
            otherDHandicapMetre: "",
            otherDTxt: "Ballygur Star",
            otherDogId: 545122,
            otherDogName: "Ballygur Star",
            outcomeDesc: "5th",
            rOutcomeId: "5",
            raceGradeId: "9",
            raceId: 1883412,
            raceTime: "2022-01-20 08:27",
            raceTitle: "Covid-19 Protocols 525",
            resultDate: "20Jan22",
            resultsAvailable: 1,
            sectionalTime: "3.30",
            shortTracName: "Wtrfd",
            trackId: "58",
            trackName: "WATERFORD",
            trap: "3",
            trialFlag: "NT",
            typeCde: "F",
            videoid: "",
            weight: "36.4",
            winnersTimeS: "29.16",
          },
          {
            bndPos: "1111",
            by: "&frac12",
            calcRTimes: "29.46",
            clipId: "",
            closeUpCmnt: "EvCh,DispLd",
            handicapMetre: "",
            distanceTitle: "480m",
            goingType: "N",
            gradeCde: "A4",
            oddsDesc: "6/4F",
            otherDHandicapMetre: "",
            otherDTxt: "Joe Nuggets",
            otherDogId: 549344,
            otherDogName: "Joe Nuggets",
            outcomeDesc: "2nd",
            rOutcomeId: "2",
            raceGradeId: "9",
            raceId: 1880704,
            raceTime: "2022-01-06 09:52",
            raceTitle: "Sis Racing From Waterford 525",
            resultDate: "06Jan22",
            resultsAvailable: 1,
            sectionalTime: "3.29",
            shortTracName: "Wtrfd",
            trackId: "58",
            trackName: "WATERFORD",
            trap: "2",
            trialFlag: "NT",
            typeCde: "F",
            videoid: "",
            weight: "36.4",
            winnersTimeS: "29.43",
          },
          {
            bndPos: "3333",
            by: "4&frac12",
            calcRTimes: "29.48",
            clipId: "",
            closeUpCmnt: "EP,AHandy",
            handicapMetre: "",
            distanceTitle: "480m",
            goingType: "+10",
            gradeCde: "A4",
            oddsDesc: "6/4F",
            otherDHandicapMetre: "",
            otherDTxt: "Bing Darcy",
            otherDogId: 547522,
            otherDogName: "Bing Darcy",
            outcomeDesc: "3rd",
            rOutcomeId: "3",
            raceGradeId: "9",
            raceId: 1879372,
            raceTime: "2021-12-30 08:27",
            raceTitle: "Greyhounds Make Great Pets 525",
            resultDate: "30Dec21",
            resultsAvailable: 1,
            sectionalTime: "3.28",
            shortTracName: "Wtrfd",
            trackId: "58",
            trackName: "WATERFORD",
            trap: "3",
            trialFlag: "NT",
            typeCde: "F",
            videoid: "",
            weight: "35.9",
            winnersTimeS: "29.07",
          },
          {
            bndPos: "1111",
            by: "nk",
            calcRTimes: "29.38",
            clipId: "",
            closeUpCmnt: "Ld1-NrLn",
            handicapMetre: "",
            distanceTitle: "480m",
            goingType: "+20",
            gradeCde: "A4",
            oddsDesc: "5/2",
            otherDHandicapMetre: "",
            otherDTxt: "Playboy Chap",
            otherDogId: 549997,
            otherDogName: "Playboy Chap",
            outcomeDesc: "2nd",
            rOutcomeId: "2",
            raceGradeId: "9",
            raceId: 1878694,
            raceTime: "2021-12-23 08:27",
            raceTitle: "Deanann Cu Peata Maith 525",
            resultDate: "23Dec21",
            resultsAvailable: 1,
            sectionalTime: "3.27",
            shortTracName: "Wtrfd",
            trackId: "58",
            trackName: "WATERFORD",
            trap: "2",
            trialFlag: "NT",
            typeCde: "F",
            videoid: "",
            weight: "35.9",
            winnersTimeS: "29.16",
          },
        ],
      },
      {
        bestTimeGrade: "A7",
        bestTimeGradeDate: "6Jan22",
        birthMonYY: "Sep19",
        brt: "29.47",
        chanceOfWin: "",
        dam: "Whiteys Sunrise",
        dateOfBirth: "28Sep19",
        dateOfSeason: "",
        diffusionName: "WHITEYS_DAWN",
        dogColor: "BK",
        dogId: "556361",
        dogName: "Whiteys Dawn",
        dogSex: "B",
        forecast: "11/2",
        forecastComment: "May not have necessary tackle for this task",
        handicapMetre: "",
        isVacant: false,
        nonRunner: "Y",
        reserved: "",
        shortForm: "",
        sire: "Sparta Maestro",
        spotlightComment: "",
        topSpeed: "99",
        trackId: "58",
        trainerLocation: "",
        trainerName: "C Tuohy",
        trapNum: "2",
        wideYn: "",
        forms: [
          {
            bndPos: "3344",
            by: "12&frac14",
            calcRTimes: "30.34",
            clipId: "",
            closeUpCmnt: "EP,Fdd",
            handicapMetre: "",
            distanceTitle: "480m",
            goingType: "+30",
            gradeCde: "A4",
            oddsDesc: "10/1",
            otherDHandicapMetre: "",
            otherDTxt: "Playboy Chap",
            otherDogId: 549997,
            otherDogName: "Playboy Chap",
            outcomeDesc: "4th",
            rOutcomeId: "4",
            raceGradeId: "9",
            raceId: 1884810,
            raceTime: "2022-01-27 10:23",
            raceTitle: "Sis Racing From Waterford 525",
            resultDate: "27Jan22",
            resultsAvailable: 1,
            sectionalTime: "3.26",
            shortTracName: "Wtrfd",
            trackId: "58",
            trackName: "WATERFORD",
            trap: "5",
            trialFlag: "NT",
            typeCde: "F",
            videoid: "",
            weight: "29.5",
            winnersTimeS: "29.18",
          },
          {
            bndPos: "1111",
            by: "1&frac12",
            calcRTimes: "29.55",
            clipId: "",
            closeUpCmnt: "EP,Ld1",
            handicapMetre: "",
            distanceTitle: "480m",
            goingType: "N",
            gradeCde: "A4",
            oddsDesc: "8/1",
            otherDHandicapMetre: "",
            otherDTxt: "Nans Spark",
            otherDogId: 539914,
            otherDogName: "Nans Spark",
            outcomeDesc: "3rd",
            rOutcomeId: "3",
            raceGradeId: "9",
            raceId: 1882113,
            raceTime: "2022-01-13 08:27",
            raceTitle: "Irish Retired Greyhound Trust 525",
            resultDate: "13Jan22",
            resultsAvailable: 1,
            sectionalTime: "3.17",
            shortTracName: "Wtrfd",
            trackId: "58",
            trackName: "WATERFORD",
            trap: "2",
            trialFlag: "NT",
            typeCde: "F",
            videoid: "",
            weight: "30.0",
            winnersTimeS: "29.45",
          },
          {
            bndPos: "1111",
            by: "shd",
            calcRTimes: "29.47",
            clipId: "",
            closeUpCmnt: "DispLd,Ld-NrLn",
            handicapMetre: "",
            distanceTitle: "480m",
            goingType: "N",
            gradeCde: "A7",
            oddsDesc: "2/1J",
            otherDHandicapMetre: "",
            otherDTxt: "Jackadam",
            otherDogId: 558353,
            otherDogName: "Jackadam",
            outcomeDesc: "2nd",
            rOutcomeId: "2",
            raceGradeId: "12",
            raceId: 1880701,
            raceTime: "2022-01-06 09:02",
            raceTitle: "Upcoming Events @ Kilcohan Park 525",
            resultDate: "06Jan22",
            resultsAvailable: 1,
            sectionalTime: "3.19",
            shortTracName: "Wtrfd",
            trackId: "58",
            trackName: "WATERFORD",
            trap: "1",
            trialFlag: "NT",
            typeCde: "F",
            videoid: "",
            weight: "30.0",
            winnersTimeS: "29.46",
          },
          {
            bndPos: "6666",
            by: "16",
            calcRTimes: "30.70",
            clipId: "",
            closeUpCmnt: "BlkTrps,NvrShwd",
            handicapMetre: "",
            distanceTitle: "480m",
            goingType: "+20",
            gradeCde: "A6",
            oddsDesc: "2/1F",
            otherDHandicapMetre: "",
            otherDTxt: "Memphis Misses",
            otherDogId: 552293,
            otherDogName: "Memphis Misses",
            outcomeDesc: "6th",
            rOutcomeId: "6",
            raceGradeId: "11",
            raceId: 1878695,
            raceTime: "2021-12-23 08:43",
            raceTitle: "Waterford Track Supporters Club 525",
            resultDate: "23Dec21",
            resultsAvailable: 1,
            sectionalTime: "3.65",
            shortTracName: "Wtrfd",
            trackId: "58",
            trackName: "WATERFORD",
            trap: "4",
            trialFlag: "NT",
            typeCde: "F",
            videoid: "",
            weight: "30.5",
            winnersTimeS: "29.38",
          },
          {
            bndPos: "1111",
            by: "1",
            calcRTimes: "29.86",
            clipId: "",
            closeUpCmnt: "EP,Ld1",
            handicapMetre: "",
            distanceTitle: "480m",
            goingType: "+30",
            gradeCde: "A6",
            oddsDesc: "5/2C",
            otherDHandicapMetre: "",
            otherDTxt: "Go Star Go",
            otherDogId: 554931,
            otherDogName: "Go Star Go",
            outcomeDesc: "2nd",
            rOutcomeId: "2",
            raceGradeId: "11",
            raceId: 1875851,
            raceTime: "2021-12-09 08:43",
            raceTitle: "Book Your Trials Online 525",
            resultDate: "09Dec21",
            resultsAvailable: 1,
            sectionalTime: "3.25",
            shortTracName: "Wtrfd",
            trackId: "58",
            trackName: "WATERFORD",
            trap: "1",
            trialFlag: "NT",
            typeCde: "F",
            videoid: "",
            weight: "30.0",
            winnersTimeS: "29.49",
          },
        ],
      },
      {
        bestTimeGrade: "A5",
        bestTimeGradeDate: "13Jan22",
        birthMonYY: "May18",
        brt: "29.31",
        chanceOfWin: "",
        dam: "Glenbervie Anne",
        dateOfBirth: "01May18",
        dateOfSeason: "",
        diffusionName: "GLENBERVIE_ELSA",
        dogColor: "BK",
        dogId: "543554",
        dogName: "Glenbervie Elsa",
        dogSex: "B",
        forecast: "9/2",
        forecastComment: "Degree of margin for error but mustn't over-egg it",
        handicapMetre: "",
        isVacant: false,
        nonRunner: "Y",
        reserved: "",
        shortForm: "",
        sire: "Droopys Jet",
        spotlightComment: "",
        topSpeed: "100",
        trackId: "58",
        trainerLocation: "",
        trainerName: "D O'Regan",
        trapNum: "3",
        wideYn: "",
        forms: [
          {
            bndPos: "4321",
            by: "1",
            calcRTimes: "29.52",
            clipId: "",
            closeUpCmnt: "EvCh,Chl3",
            handicapMetre: "",
            distanceTitle: "480m",
            goingType: "+20",
            gradeCde: "A5",
            oddsDesc: "6/1",
            otherDHandicapMetre: "",
            otherDTxt: "Joe Nuggets",
            otherDogId: 549344,
            otherDogName: "Joe Nuggets",
            outcomeDesc: "2nd",
            rOutcomeId: "2",
            raceGradeId: "10",
            raceId: 1887533,
            raceTime: "2022-02-10 10:41",
            raceTitle: "Rasaiocht Con Eireann 525",
            resultDate: "10Feb22",
            resultsAvailable: 1,
            sectionalTime: "3.32",
            shortTracName: "Wtrfd",
            trackId: "58",
            trackName: "WATERFORD",
            trap: "1",
            trialFlag: "NT",
            typeCde: "F",
            videoid: "",
            weight: "27.3",
            winnersTimeS: "29.25",
          },
          {
            bndPos: "4321",
            by: "2",
            calcRTimes: "29.69",
            clipId: "",
            closeUpCmnt: "EvCh,Ld3/4",
            handicapMetre: "",
            distanceTitle: "480m",
            goingType: "+10",
            gradeCde: "A4",
            oddsDesc: "11/2",
            otherDHandicapMetre: "",
            otherDTxt: "Almighty Gerry",
            otherDogId: 555078,
            otherDogName: "Almighty Gerry",
            outcomeDesc: "2nd",
            rOutcomeId: "2",
            raceGradeId: "9",
            raceId: 1886136,
            raceTime: "2022-02-03 09:52",
            raceTitle: "Barking Buzz 525",
            resultDate: "03Feb22",
            resultsAvailable: 1,
            sectionalTime: "3.35",
            shortTracName: "Wtrfd",
            trackId: "58",
            trackName: "WATERFORD",
            trap: "2",
            trialFlag: "NT",
            typeCde: "F",
            videoid: "",
            weight: "27.3",
            winnersTimeS: "29.45",
          },
          {
            bndPos: "3443",
            by: "10&frac12",
            calcRTimes: "31.20",
            clipId: "",
            closeUpCmnt: "SAw,NvrShwd",
            handicapMetre: "",
            distanceTitle: "503m",
            goingType: "N",
            gradeCde: "A4",
            oddsDesc: "",
            otherDHandicapMetre: "",
            otherDTxt: "Bogger Biggav",
            otherDogId: null,
            otherDogName: "Bogger Biggav",
            outcomeDesc: "5th",
            rOutcomeId: "5",
            raceGradeId: "9",
            raceId: 1885520,
            raceTime: "2022-01-31 20:21",
            raceTitle: "Hotel Minella A4 550 Stake Semi-Final",
            resultDate: "31Jan22",
            resultsAvailable: 1,
            sectionalTime: "4.46",
            shortTracName: "Clnml",
            trackId: "41",
            trackName: "CLONMEL",
            trap: "2",
            trialFlag: "NT",
            typeCde: "F",
            videoid: "",
            weight: "26.4",
            winnersTimeS: "30.47",
          },
          {
            bndPos: "2211",
            by: "&frac12",
            calcRTimes: "29.53",
            clipId: "",
            closeUpCmnt: "EvCh,Ld3",
            handicapMetre: "",
            distanceTitle: "480m",
            goingType: "+10",
            gradeCde: "A4",
            oddsDesc: "10/1",
            otherDHandicapMetre: "",
            otherDTxt: "Placid Pilgrim",
            otherDogId: 553810,
            otherDogName: "Placid Pilgrim",
            outcomeDesc: "2nd",
            rOutcomeId: "2",
            raceGradeId: "9",
            raceId: 1883420,
            raceTime: "2022-01-20 10:41",
            raceTitle: "Barking Buzz 525",
            resultDate: "20Jan22",
            resultsAvailable: 1,
            sectionalTime: "3.33",
            shortTracName: "Wtrfd",
            trackId: "58",
            trackName: "WATERFORD",
            trap: "1",
            trialFlag: "NT",
            typeCde: "F",
            videoid: "",
            weight: "27.3",
            winnersTimeS: "29.40",
          },
          {
            bndPos: "5322",
            by: "2&frac12",
            calcRTimes: "29.31",
            clipId: "",
            closeUpCmnt: "AHandy,RnOn",
            handicapMetre: "",
            distanceTitle: "480m",
            goingType: "N",
            gradeCde: "A5",
            oddsDesc: "10/1",
            otherDHandicapMetre: "",
            otherDTxt: "Brynoffa Ron",
            otherDogId: 553422,
            otherDogName: "Brynoffa Ron",
            outcomeDesc: "2nd",
            rOutcomeId: "2",
            raceGradeId: "10",
            raceId: 1882120,
            raceTime: "2022-01-13 10:23",
            raceTitle: "Book Your Trials Online 525",
            resultDate: "13Jan22",
            resultsAvailable: 1,
            sectionalTime: "3.33",
            shortTracName: "Wtrfd",
            trackId: "58",
            trackName: "WATERFORD",
            trap: "2",
            trialFlag: "NT",
            typeCde: "F",
            videoid: "",
            weight: "26.8",
            winnersTimeS: "29.14",
          },
        ],
      },
      {
        bestTimeGrade: "A4",
        bestTimeGradeDate: "6Jan22",
        birthMonYY: "Oct19",
        brt: "29.26",
        chanceOfWin: "",
        dam: "Jumbos Vixen",
        dateOfBirth: "17Oct19",
        dateOfSeason: "",
        diffusionName: "MONEY_MISER",
        dogColor: "BK",
        dogId: "555287",
        dogName: "Money Miser",
        dogSex: "D",
        forecast: "5/1",
        forecastComment: "The four-box can work wonders these days",
        handicapMetre: "",
        isVacant: false,
        nonRunner: "Y",
        reserved: "",
        shortForm: "",
        sire: "Skywalker Farloe",
        spotlightComment: "",
        topSpeed: "99",
        trackId: "58",
        trainerLocation: "",
        trainerName: " The-Cats-Got-The-Cream-Syndi.",
        trapNum: "4",
        wideYn: "",
        forms: [
          {
            bndPos: "3435",
            by: "5&frac34",
            calcRTimes: "29.84",
            clipId: "",
            closeUpCmnt: "MsdBrk,EP",
            handicapMetre: "",
            distanceTitle: "480m",
            goingType: "+20",
            gradeCde: "A5",
            oddsDesc: "5/1",
            otherDHandicapMetre: "",
            otherDTxt: "Joe Nuggets",
            otherDogId: 549344,
            otherDogName: "Joe Nuggets",
            outcomeDesc: "5th",
            rOutcomeId: "5",
            raceGradeId: "10",
            raceId: 1887533,
            raceTime: "2022-02-10 10:41",
            raceTitle: "Rasaiocht Con Eireann 525",
            resultDate: "10Feb22",
            resultsAvailable: 1,
            sectionalTime: "3.26",
            shortTracName: "Wtrfd",
            trackId: "58",
            trackName: "WATERFORD",
            trap: "5",
            trialFlag: "NT",
            typeCde: "F",
            videoid: "",
            weight: "33.2",
            winnersTimeS: "29.25",
          },
          {
            bndPos: "4333",
            by: "5",
            calcRTimes: "29.51",
            clipId: "",
            closeUpCmnt: "EP,Mid",
            handicapMetre: "",
            distanceTitle: "480m",
            goingType: "+10",
            gradeCde: "A3",
            oddsDesc: "",
            otherDHandicapMetre: "",
            otherDTxt: "Mister Audacity",
            otherDogId: 555375,
            otherDogName: "Mister Audacity",
            outcomeDesc: "3rd",
            rOutcomeId: "3",
            raceGradeId: "8",
            raceId: 1886140,
            raceTime: "2022-02-03 10:52",
            raceTitle: "Slan Abhaile 525 Non Sis",
            resultDate: "03Feb22",
            resultsAvailable: 1,
            sectionalTime: "3.33",
            shortTracName: "Wtrfd",
            trackId: "58",
            trackName: "WATERFORD",
            trap: "1",
            trialFlag: "NT",
            typeCde: "F",
            videoid: "",
            weight: "32.7",
            winnersTimeS: "29.06",
          },
          {
            bndPos: "2666",
            by: "dist",
            calcRTimes: "0.00",
            clipId: "",
            closeUpCmnt: "KO2",
            handicapMetre: "",
            distanceTitle: "480m",
            goingType: "+30",
            gradeCde: "A4",
            oddsDesc: "5/1",
            otherDHandicapMetre: "",
            otherDTxt: "Playboy Chap",
            otherDogId: 549997,
            otherDogName: "Playboy Chap",
            outcomeDesc: "6th",
            rOutcomeId: "6",
            raceGradeId: "9",
            raceId: 1884810,
            raceTime: "2022-01-27 10:23",
            raceTitle: "Sis Racing From Waterford 525",
            resultDate: "27Jan22",
            resultsAvailable: 1,
            sectionalTime: "3.29",
            shortTracName: "Wtrfd",
            trackId: "58",
            trackName: "WATERFORD",
            trap: "3",
            trialFlag: "NT",
            typeCde: "F",
            videoid: "",
            weight: "32.7",
            winnersTimeS: "29.18",
          },
          {
            bndPos: "6665",
            by: "2&frac14",
            calcRTimes: "29.58",
            clipId: "",
            closeUpCmnt: "Outp,Styd",
            handicapMetre: "",
            distanceTitle: "480m",
            goingType: "N",
            gradeCde: "A3",
            oddsDesc: "7/1",
            otherDHandicapMetre: "",
            otherDTxt: "Placid Pilgrim",
            otherDogId: 553810,
            otherDogName: "Placid Pilgrim",
            outcomeDesc: "6th",
            rOutcomeId: "6",
            raceGradeId: "8",
            raceId: 1882118,
            raceTime: "2022-01-13 09:52",
            raceTitle: "Early Start Saturday Nights 525",
            resultDate: "13Jan22",
            resultsAvailable: 1,
            sectionalTime: "3.32",
            shortTracName: "Wtrfd",
            trackId: "58",
            trackName: "WATERFORD",
            trap: "4",
            trialFlag: "NT",
            typeCde: "F",
            videoid: "",
            weight: "32.7",
            winnersTimeS: "29.43",
          },
          {
            bndPos: "2223",
            by: "1",
            calcRTimes: "29.26",
            clipId: "",
            closeUpCmnt: "AHandy,FnWll",
            handicapMetre: "",
            distanceTitle: "480m",
            goingType: "N",
            gradeCde: "A4",
            oddsDesc: "8/1",
            otherDHandicapMetre: "",
            otherDTxt: "Nans Falcon",
            otherDogId: 553928,
            otherDogName: "Nans Falcon",
            outcomeDesc: "2nd",
            rOutcomeId: "2",
            raceGradeId: "9",
            raceId: 1880700,
            raceTime: "2022-01-06 08:43",
            raceTitle: "Waterford Track Supporters Club 525",
            resultDate: "06Jan22",
            resultsAvailable: 1,
            sectionalTime: "3.23",
            shortTracName: "Wtrfd",
            trackId: "58",
            trackName: "WATERFORD",
            trap: "3",
            trialFlag: "NT",
            typeCde: "F",
            videoid: "",
            weight: "33.2",
            winnersTimeS: "29.19",
          },
        ],
      },
      {
        bestTimeGrade: "A2",
        bestTimeGradeDate: "18Nov21",
        birthMonYY: "Jan19",
        brt: "29.28",
        chanceOfWin: "",
        dam: "Lough Maeve",
        dateOfBirth: "03Jan19",
        dateOfSeason: "",
        diffusionName: "RISK_IT_BLUE",
        dogColor: "BE",
        dogId: "549114",
        dogName: "Risk It Blue",
        dogSex: "D",
        forecast: "4/1",
        forecastComment: "Needs to stay away from trouble spots, not easy",
        handicapMetre: "",
        isVacant: false,
        nonRunner: "Y",
        reserved: "",
        shortForm: "",
        sire: "Over Limit",
        spotlightComment: "",
        topSpeed: "95",
        trackId: "58",
        trainerLocation: "",
        trainerName: "P O'Neill",
        trapNum: "5",
        wideYn: "M",
        forms: [
          {
            bndPos: "6634",
            by: "5&frac14",
            calcRTimes: "29.86",
            clipId: "",
            closeUpCmnt: "Crd1,Styd",
            handicapMetre: "",
            distanceTitle: "480m",
            goingType: "+10",
            gradeCde: "A5",
            oddsDesc: "11/4",
            otherDHandicapMetre: "",
            otherDTxt: "Almighty Emma",
            otherDogId: 553423,
            otherDogName: "Almighty Emma",
            outcomeDesc: "5th",
            rOutcomeId: "5",
            raceGradeId: "10",
            raceId: 1886130,
            raceTime: "2022-02-03 08:12",
            raceTitle: "Failte Go Dti Staid Kilcohan Park Na Gcon 525",
            resultDate: "03Feb22",
            resultsAvailable: 1,
            sectionalTime: "3.38",
            shortTracName: "Wtrfd",
            trackId: "58",
            trackName: "WATERFORD",
            trap: "1",
            trialFlag: "NT",
            typeCde: "F",
            videoid: "",
            weight: "31.8",
            winnersTimeS: "29.40",
          },
          {
            bndPos: "6666",
            by: "5",
            calcRTimes: "29.86",
            clipId: "",
            closeUpCmnt: "CrdRnUp,FnWll",
            handicapMetre: "",
            distanceTitle: "480m",
            goingType: "+30",
            gradeCde: "A5",
            oddsDesc: "2/1F",
            otherDHandicapMetre: "",
            otherDTxt: "Slaneyside Mel",
            otherDogId: 556683,
            otherDogName: "Slaneyside Mel",
            outcomeDesc: "3rd",
            rOutcomeId: "3",
            raceGradeId: "10",
            raceId: 1884802,
            raceTime: "2022-01-27 08:12",
            raceTitle: "Failte Go Dti Kilcohan Park 525",
            resultDate: "27Jan22",
            resultsAvailable: 1,
            sectionalTime: "3.38",
            shortTracName: "Wtrfd",
            trackId: "58",
            trackName: "WATERFORD",
            trap: "1",
            trialFlag: "NT",
            typeCde: "F",
            videoid: "",
            weight: "31.8",
            winnersTimeS: "29.21",
          },
          {
            bndPos: "4442",
            by: "3",
            calcRTimes: "29.47",
            clipId: "",
            closeUpCmnt: "Rls1,FnWll",
            handicapMetre: "",
            distanceTitle: "480m",
            goingType: "+10",
            gradeCde: "A4",
            oddsDesc: "10/1",
            otherDHandicapMetre: "",
            otherDTxt: "Ballygur Star",
            otherDogId: 545122,
            otherDogName: "Ballygur Star",
            outcomeDesc: "2nd",
            rOutcomeId: "2",
            raceGradeId: "9",
            raceId: 1883412,
            raceTime: "2022-01-20 08:27",
            raceTitle: "Covid-19 Protocols 525",
            resultDate: "20Jan22",
            resultsAvailable: 1,
            sectionalTime: "3.34",
            shortTracName: "Wtrfd",
            trackId: "58",
            trackName: "WATERFORD",
            trap: "2",
            trialFlag: "NT",
            typeCde: "F",
            videoid: "",
            weight: "32.7",
            winnersTimeS: "29.16",
          },
          {
            bndPos: "5554",
            by: "5&frac34",
            calcRTimes: "30.05",
            clipId: "",
            closeUpCmnt: "MsdBrk,Fcd-Ck2",
            handicapMetre: "",
            distanceTitle: "480m",
            goingType: "N",
            gradeCde: "A4",
            oddsDesc: "",
            otherDHandicapMetre: "",
            otherDTxt: "Brynoffa Jenson",
            otherDogId: 557188,
            otherDogName: "Brynoffa Jenson",
            outcomeDesc: "4th",
            rOutcomeId: "4",
            raceGradeId: "9",
            raceId: 1880708,
            raceTime: "2022-01-06 10:52",
            raceTitle: "Slan Abhaile 525 Non Sis",
            resultDate: "06Jan22",
            resultsAvailable: 1,
            sectionalTime: "3.33",
            shortTracName: "Wtrfd",
            trackId: "58",
            trackName: "WATERFORD",
            trap: "2",
            trialFlag: "NT",
            typeCde: "F",
            videoid: "",
            weight: "33.2",
            winnersTimeS: "29.65",
          },
          {
            bndPos: "5555",
            by: "9",
            calcRTimes: "30.36",
            clipId: "",
            closeUpCmnt: null,
            handicapMetre: "",
            distanceTitle: "480m",
            goingType: "-50",
            gradeCde: "A4",
            oddsDesc: "5/1",
            otherDHandicapMetre: "",
            otherDTxt: "Tomahurra Zeus",
            otherDogId: null,
            otherDogName: "Tomahurra Zeus",
            outcomeDesc: "5th",
            rOutcomeId: "5",
            raceGradeId: "9",
            raceId: 1879110,
            raceTime: "2021-12-30 16:45",
            raceTitle: "Talking Dogs News 525",
            resultDate: "30Dec21",
            resultsAvailable: 1,
            sectionalTime: "",
            shortTracName: "Ennis",
            trackId: "48",
            trackName: "ENNISCORTHY",
            trap: "2",
            trialFlag: "NT",
            typeCde: "F",
            videoid: "",
            weight: "32.3",
            winnersTimeS: "30.23",
          },
        ],
      },
      {
        bestTimeGrade: "A6",
        bestTimeGradeDate: "23Dec21",
        birthMonYY: "Jul20",
        brt: "29.42",
        chanceOfWin: "",
        dam: "Slaneyside Sofia",
        dateOfBirth: "01Jul20",
        dateOfSeason: "",
        diffusionName: "SLANEYSIDE_MEL",
        dogColor: "BE",
        dogId: "556683",
        dogName: "Slaneyside Mel",
        dogSex: "B",
        forecast: "9/4",
        forecastComment: "Has ability, hence bookies keep the price down",
        handicapMetre: "",
        isVacant: false,
        nonRunner: "Y",
        reserved: "",
        shortForm: "",
        sire: "Jaytee Jet",
        spotlightComment: "",
        topSpeed: "97",
        trackId: "58",
        trainerLocation: "",
        trainerName: "D Kehoe",
        trapNum: "6",
        wideYn: "M",
        forms: [
          {
            bndPos: "6554",
            by: "4",
            calcRTimes: "29.73",
            clipId: "",
            closeUpCmnt: "SAw,FnWll",
            handicapMetre: "",
            distanceTitle: "480m",
            goingType: "+20",
            gradeCde: "A5",
            oddsDesc: "7/2",
            otherDHandicapMetre: "",
            otherDTxt: "Joe Nuggets",
            otherDogId: 549344,
            otherDogName: "Joe Nuggets",
            outcomeDesc: "3rd",
            rOutcomeId: "3",
            raceGradeId: "10",
            raceId: 1887533,
            raceTime: "2022-02-10 10:41",
            raceTitle: "Rasaiocht Con Eireann 525",
            resultDate: "10Feb22",
            resultsAvailable: 1,
            sectionalTime: "3.30",
            shortTracName: "Wtrfd",
            trackId: "58",
            trackName: "WATERFORD",
            trap: "6",
            trialFlag: "NT",
            typeCde: "F",
            videoid: "",
            weight: "29.1",
            winnersTimeS: "29.25",
          },
          {
            bndPos: "4433",
            by: "2&frac12",
            calcRTimes: "29.81",
            clipId: "",
            closeUpCmnt: "Bmp1,StrFn",
            handicapMetre: "",
            distanceTitle: "480m",
            goingType: "+10",
            gradeCde: "A5",
            oddsDesc: "2/1",
            otherDHandicapMetre: "",
            otherDTxt: "Ballyrobin June",
            otherDogId: 549358,
            otherDogName: "Ballyrobin June",
            outcomeDesc: "2nd",
            rOutcomeId: "2",
            raceGradeId: "10",
            raceId: 1886139,
            raceTime: "2022-02-03 10:41",
            raceTitle: "This Runs Deep 525",
            resultDate: "03Feb22",
            resultsAvailable: 1,
            sectionalTime: "3.31",
            shortTracName: "Wtrfd",
            trackId: "58",
            trackName: "WATERFORD",
            trap: "6",
            trialFlag: "NT",
            typeCde: "F",
            videoid: "",
            weight: "28.6",
            winnersTimeS: "29.54",
          },
          {
            bndPos: "1111",
            by: "&frac12",
            calcRTimes: "29.51",
            clipId: "",
            closeUpCmnt: "Ld1,Styd",
            handicapMetre: "",
            distanceTitle: "480m",
            goingType: "+30",
            gradeCde: "A5",
            oddsDesc: "4/1",
            otherDHandicapMetre: "",
            otherDTxt: "Almighty Emma",
            otherDogId: 553423,
            otherDogName: "Almighty Emma",
            outcomeDesc: "1st",
            rOutcomeId: "1",
            raceGradeId: "10",
            raceId: 1884802,
            raceTime: "2022-01-27 08:12",
            raceTitle: "Failte Go Dti Kilcohan Park 525",
            resultDate: "27Jan22",
            resultsAvailable: 1,
            sectionalTime: "3.30",
            shortTracName: "Wtrfd",
            trackId: "58",
            trackName: "WATERFORD",
            trap: "4",
            trialFlag: "NT",
            typeCde: "F",
            videoid: "",
            weight: "28.6",
            winnersTimeS: "29.21",
          },
          {
            bndPos: "6544",
            by: "2&frac34",
            calcRTimes: "29.85",
            clipId: "",
            closeUpCmnt: "LckdEP,FnWll",
            handicapMetre: "",
            distanceTitle: "480m",
            goingType: "+10",
            gradeCde: "A5",
            oddsDesc: "5/2F",
            otherDHandicapMetre: "",
            otherDTxt: "Memphis Misses",
            otherDogId: 552293,
            otherDogName: "Memphis Misses",
            outcomeDesc: "3rd",
            rOutcomeId: "3",
            raceGradeId: "10",
            raceId: 1883416,
            raceTime: "2022-01-20 09:34",
            raceTitle: "Early Start Saturday Night 525",
            resultDate: "20Jan22",
            resultsAvailable: 1,
            sectionalTime: "3.36",
            shortTracName: "Wtrfd",
            trackId: "58",
            trackName: "WATERFORD",
            trap: "4",
            trialFlag: "NT",
            typeCde: "F",
            videoid: "",
            weight: "28.6",
            winnersTimeS: "29.57",
          },
          {
            bndPos: "5665",
            by: "1&frac34",
            calcRTimes: "29.56",
            clipId: "",
            closeUpCmnt: "Outp,StrFn",
            handicapMetre: "",
            distanceTitle: "480m",
            goingType: "N",
            gradeCde: "A4",
            oddsDesc: "11/4",
            otherDHandicapMetre: "",
            otherDTxt: "Nans Spark",
            otherDogId: 539914,
            otherDogName: "Nans Spark",
            outcomeDesc: "4th",
            rOutcomeId: "4",
            raceGradeId: "9",
            raceId: 1882113,
            raceTime: "2022-01-13 08:27",
            raceTitle: "Irish Retired Greyhound Trust 525",
            resultDate: "13Jan22",
            resultsAvailable: 1,
            sectionalTime: "3.33",
            shortTracName: "Wtrfd",
            trackId: "58",
            trackName: "WATERFORD",
            trap: "4",
            trialFlag: "NT",
            typeCde: "F",
            videoid: "",
            weight: "28.6",
            winnersTimeS: "29.45",
          },
        ],
      },
    ],
  },
};
